Add Local Compression Option
dragoonDorise/pegasus-android-metadata pull request #30
Opened 2022-05-21 06:03 UTC by SoumyBhow

This PR aims to install CHDMAN and Maxcso with the Pegasus pack along with scripts to allow easy local compression. Maxcso is used for PPSSPP and CHDMAN is used for other platforms like Saturn, PSX, PS2, etc. I redid everything from scratch and it should work now. Only mild issue is that I can't get the compressor script to output in stdout and the log file. I tried ```tee``` but that broke the script.

2022-05-21 22:09 UTC, dollerbill commented
@SoumyBhow thank you for reopening this PR! 
Everything looks great in the quick look I did, hopefully I'll be able to test it this weekend and we can look at getting it merged

2022-05-21 22:35 UTC, SoumyBhow commented
> 

Glad you liked it! Thing I'm most worried about rn is the fact that (for now) it involves ```cd```ing into each folder and compressing there. Not sure how that'll fair with the rest of the script but I tested it on Android 12L and I had no issues with that..

2022-05-25 06:45 UTC, dollerbill requested changes
Looks good, just a few really small things! I'm still testing the actual compression but hopefully I can wrap that up soon

2022-05-25 06:45 UTC, dollerbill commented on startup.sh
> -fi
```
if [[ $selected_option == "10" ]]
then
	am startservice -a com.termux.service_stop com.termux/.app.TermuxService &> /dev/null
fi 
```

Let's get the exit option added back in

2022-05-25 06:45 UTC, dollerbill commented on compress.sh
> +SYSTEMS=$(whiptail --title "ROM Compressor" --checklist "Please select the systems whose ROMs you want to compress" 20 78 15 \
```suggestion
SYSTEMS=$(whiptail --title "ROM Compressor" --checklist "Please select the systems whose ROMs you want to compress" 20 78 5 \
```

To cleanup a bit of the extra highlighting below the options

2022-05-25 06:45 UTC, dollerbill commented on compress.sh
> + echo -e "You may need to re-scrap your games after they've been compressed!"
If we wanted to we could probably check the metadata file for an existing iso/etc and replace that line with the newly scraped game path.. but it wouldn't hurt to leave as-is and add that in later

2022-05-25 18:06 UTC, SoumyBhow commented
@dollerbill Requested changes have been made. I also changed the compressor script so that instead of converting all of the ROMs and deleting the uncompressed versions in one go, it converts a ROM then deletes the old ROM one by one. This makes the script safer and doesn't eat up storage as it previously did.

2022-06-01 06:07 UTC, dollerbill commented
> @dollerbill Requested changes have been made. I also changed the compressor script so that instead of converting all of the ROMs and deleting the uncompressed versions in one go, it converts a ROM then deletes the old ROM one by one. This makes the script safer and doesn't eat up storage as it previously did.

this is a great addition, one of my earlier concerns was potentially eating up all available storage before finishing the conversion. Glad you added it!

Taking another look now

2022-06-01 06:22 UTC, dollerbill approved these changes
Looks great! I'm gonna keep testing a bit on my device and will get it merged soon

2022-06-01 15:58 UTC, SoumyBhow commented
Thank you so much. Glad it's looking good.

2022-06-02 05:04 UTC, merged